version: "2"
services:
  spring:
    container_name: 'gmovement'
    image: gamma/g-movement
    ports:
      - '8080:8080'
    links:
      - 'db:db'
      - 'ldap:ldap'
      - 'influxdb:influxdb'
  db:
    container_name: 'gmovement_db'
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=queenelizabeth
      - POSTGRES_USER=gamma
      - POSTGRES_DB=gamma
    ports:
      - '5433:5432'
    volumes:
      - '.docker/db:/var/lib/postgresql/data'
  ldap:
    container_name: 'gmovement_ldap'
    image: dinkel/openldap
    ports:
      - '389:389'
    environment:
      - SLAPD_PASSWORD=queenelizabeth
      - SLAPD_DOMAIN=swaggabros.nl
    volumes:
      - '.docker/ldap-conf:/etc/ldap'
      - '.docker/ldap-data:/var/lib/ldap'
  grafana:
    container_name: 'grafana'
    image: grafana/grafana
    ports:
     - '80:3000'
    environment:
     - 'GF_SECURITY_ADMIN_PASSWORD=queenelizabeth'
    volumes:
     - '.docker/grafana:/var/lib/grafana'
    links:
     - 'influxdb:influxdb'
    logging: 
      driver: 'none'
  influxdb:
    container_name: 'influxdb'
    image: tutum/influxdb
    ports:
      - '8083:8083'
      - '8086:8086'
    environment:
      - 'PRE_CREATE_DB=gmovement'
    volumes:
      - '.docker/influxdb:/data'
    logging: 
      driver: 'none'
