db:
  image: postgres:alpine
  environment:
    - POSTGRES_PASSWORD=queenelizabeth
    - POSTGRES_USER=gamma
    - POSTGRES_DB=gamma
  ports:
    - '5432:5432'
  volumes:
    - '.docker/db:/var/lib/postgresql/data'
ldap:
  image: dinkel/openldap
  ports:
    - '389:389'
  environment:
    - SLAPD_PASSWORD=queenelizabeth
    - SLAPD_DOMAIN=swaggabros.nl
  volumes:
    - '.docker/ldap-conf:/etc/ldap'
    - '.docker/ldap-data:/var/lib/ldap' 
